package com.farnam.mhrvf

// Generated by tools/generate-readiness-contract.ps1 from src/readiness.rs.
// Do not edit by hand; update Rust readiness IDs/repair targets and regenerate.
object ReadinessIds {
    const val CONFIG_VERSION = "config.version"
    const val CONFIG_MODE = "config.mode"
    const val ACCOUNT_GROUPS_ENABLED = "account_groups.enabled"
    const val ACCOUNT_GROUPS_SCRIPT_IDS = "account_groups.script_ids"
    const val ACCOUNT_GROUPS_AUTH_KEY = "account_groups.auth_key"
    const val VERCEL_BASE_URL = "vercel.base_url"
    const val VERCEL_RELAY_PATH = "vercel.relay_path"
    const val VERCEL_AUTH_KEY = "vercel.auth_key"
    const val VERCEL_MAX_BODY_BYTES = "vercel.max_body_bytes"
    const val DIRECT_GOOGLE_IP = "direct.google_ip"
    const val DIRECT_FRONT_DOMAIN = "direct.front_domain"
    const val LOCAL_LISTENER = "local.listener"
    const val LOCAL_PORTS = "local.ports"
    const val CA_TRUST = "ca.trust"
    const val ANDROID_APP_CA_TRUST = "ca.android_app_trust"
    const val LAN_EXPOSURE = "lan.exposure"
    const val LAN_TOKEN = "lan.token"
    const val LAN_ALLOWLIST = "lan.allowlist"
    const val FULL_CODEFULL_DEPLOYMENT = "full.codefull_deployment"
    const val FULL_TUNNEL_NODE_URL = "full.tunnel_node_url"
    const val FULL_TUNNEL_AUTH = "full.tunnel_auth"
    const val FULL_UDP_SUPPORT = "full.udp_support"
    const val FULL_TUNNEL_HEALTH = "full.tunnel_health"
    const val SCAN_BATCH_SIZE = "scan.batch_size"
    const val RELAY_RATE_LIMIT_QPS = "relay.rate_limit_qps"
    const val DOMAIN_OVERRIDES_HOST = "domain_overrides.host"
    const val DOMAIN_OVERRIDES_FORCE_ROUTE = "domain_overrides.force_route"
    const val FRONTING_GROUPS_NAME = "fronting_groups.name"
    const val FRONTING_GROUPS_IP = "fronting_groups.ip"
    const val FRONTING_GROUPS_SNI = "fronting_groups.sni"
    const val FRONTING_GROUPS_DOMAINS = "fronting_groups.domains"
    const val ANDROID_CONNECTION_MODE = "android.connection_mode"
}

object ReadinessRepairTargets {
    fun targetForId(id: String): String? = when (id) {
        ReadinessIds.CONFIG_VERSION -> "config.version"
        ReadinessIds.CONFIG_MODE -> "setup.mode"
        ReadinessIds.ACCOUNT_GROUPS_ENABLED -> "setup.account_groups"
        ReadinessIds.ACCOUNT_GROUPS_SCRIPT_IDS -> "setup.account_groups.script_ids"
        ReadinessIds.ACCOUNT_GROUPS_AUTH_KEY -> "setup.account_groups.auth_key"
        ReadinessIds.VERCEL_BASE_URL -> "setup.serverless.base_url"
        ReadinessIds.VERCEL_RELAY_PATH -> "setup.serverless.relay_path"
        ReadinessIds.VERCEL_AUTH_KEY -> "setup.serverless.auth_key"
        ReadinessIds.VERCEL_MAX_BODY_BYTES -> "advanced.serverless.max_body_bytes"
        ReadinessIds.DIRECT_GOOGLE_IP -> "setup.direct.google_ip"
        ReadinessIds.DIRECT_FRONT_DOMAIN -> "setup.direct.front_domain"
        ReadinessIds.LOCAL_LISTENER -> "setup.local_listener"
        ReadinessIds.LOCAL_PORTS -> "setup.local_listener.ports"
        ReadinessIds.CA_TRUST -> "setup.ca_trust"
        ReadinessIds.ANDROID_APP_CA_TRUST -> "help.android.ca_trust"
        ReadinessIds.LAN_EXPOSURE -> "network.lan.listen_host"
        ReadinessIds.LAN_TOKEN -> "network.lan.access_control"
        ReadinessIds.LAN_ALLOWLIST -> "network.lan.allowlist"
        ReadinessIds.FULL_CODEFULL_DEPLOYMENT -> "help.full.codefull"
        ReadinessIds.FULL_TUNNEL_NODE_URL -> "help.full.tunnel_node_url"
        ReadinessIds.FULL_TUNNEL_AUTH -> "help.full.tunnel_auth"
        ReadinessIds.FULL_UDP_SUPPORT -> "network.local_socks5"
        ReadinessIds.FULL_TUNNEL_HEALTH -> "help.full.tunnel_health"
        ReadinessIds.SCAN_BATCH_SIZE -> "advanced.scan.batch_size"
        ReadinessIds.RELAY_RATE_LIMIT_QPS -> "advanced.relay_rate_limit_qps"
        ReadinessIds.DOMAIN_OVERRIDES_HOST -> "advanced.domain_overrides.host"
        ReadinessIds.DOMAIN_OVERRIDES_FORCE_ROUTE -> "advanced.domain_overrides.force_route"
        ReadinessIds.FRONTING_GROUPS_NAME -> "advanced.fronting_groups.name"
        ReadinessIds.FRONTING_GROUPS_IP -> "advanced.fronting_groups.ip"
        ReadinessIds.FRONTING_GROUPS_SNI -> "advanced.fronting_groups.sni"
        ReadinessIds.FRONTING_GROUPS_DOMAINS -> "advanced.fronting_groups.domains"
        else -> null
    }
}

data class ReadinessRepairAnchor(val desktop: String, val android: String)

object ReadinessRepairAnchors {
    fun anchorForTarget(target: String): ReadinessRepairAnchor? = when (target) {
        "config.version" -> ReadinessRepairAnchor("Config file -> config_version compatibility", "Imported config file -> config_version compatibility")
        "setup.mode" -> ReadinessRepairAnchor("Setup -> Mode", "Mode section -> Mode dropdown")
        "setup.account_groups" -> ReadinessRepairAnchor("Advanced -> Multi-account pools -> Add group", "Apps Script relay -> Deployment IDs")
        "setup.account_groups.script_ids" -> ReadinessRepairAnchor("Advanced -> Multi-account pools -> IDs", "Apps Script relay -> Deployment IDs")
        "setup.account_groups.auth_key" -> ReadinessRepairAnchor("Advanced -> Multi-account pools -> Auth key", "Apps Script relay -> AUTH_KEY")
        "setup.serverless.base_url" -> ReadinessRepairAnchor("Setup -> Serverless JSON relay -> Base URL", "Serverless JSON relay -> Base URL")
        "setup.serverless.relay_path" -> ReadinessRepairAnchor("Setup -> Serverless JSON relay -> Relay path", "Serverless JSON relay -> Relay path")
        "setup.serverless.auth_key" -> ReadinessRepairAnchor("Setup -> Serverless JSON relay -> Auth key", "Serverless JSON relay -> AUTH_KEY")
        "advanced.serverless.max_body_bytes" -> ReadinessRepairAnchor("Setup -> Serverless JSON relay -> Max body MB", "Advanced config import -> vercel.max_body_bytes")
        "setup.direct.google_ip" -> ReadinessRepairAnchor("Network -> Google IP", "Network -> Google edge IP")
        "setup.direct.front_domain" -> ReadinessRepairAnchor("Network -> Front domain", "Network -> Front SNI")
        "setup.local_listener" -> ReadinessRepairAnchor("Network -> Listen host / Ports", "Advanced -> LAN sharing plus built-in local listener defaults")
        "setup.local_listener.ports" -> ReadinessRepairAnchor("Network -> Ports", "Advanced config import -> listen_port / socks5_port")
        "setup.ca_trust" -> ReadinessRepairAnchor("Setup header -> Install CA or CLI --install-cert", "Install MITM certificate button")
        "help.android.ca_trust" -> ReadinessRepairAnchor("Help & docs -> Android CA trust", "Help -> Certificate section")
        "network.lan.listen_host" -> ReadinessRepairAnchor("Network -> Sharing and per-app routing -> Local only / Share on LAN", "Advanced -> LAN sharing")
        "network.lan.access_control" -> ReadinessRepairAnchor("Network -> Sharing and per-app routing -> LAN token / Allowed IPs", "Advanced -> LAN sharing -> LAN token / Allowed IPs")
        "network.lan.allowlist" -> ReadinessRepairAnchor("Network -> Sharing and per-app routing -> Allowed IPs", "Advanced -> LAN sharing -> Allowed IPs")
        "help.full.codefull" -> ReadinessRepairAnchor("Help & docs -> Full tunnel -> CodeFull.gs", "Help -> Full tunnel setup")
        "help.full.tunnel_node_url" -> ReadinessRepairAnchor("Help & docs -> Full tunnel -> TUNNEL_SERVER_URL", "Help -> Full tunnel setup -> tunnel-node URL")
        "help.full.tunnel_auth" -> ReadinessRepairAnchor("Help & docs -> Full tunnel -> TUNNEL_AUTH_KEY", "Help -> Full tunnel setup -> matching auth")
        "network.local_socks5" -> ReadinessRepairAnchor("Network -> Ports -> SOCKS5", "Advanced config import -> socks5_port")
        "help.full.tunnel_health" -> ReadinessRepairAnchor("Help & docs -> Full tunnel -> health/details and IP-check smoke test", "Help -> Full tunnel setup -> health and public-IP verification")
        "advanced.scan.batch_size" -> ReadinessRepairAnchor("Advanced -> Scan settings -> scan_batch_size", "Advanced config import -> scan_batch_size")
        "advanced.relay_rate_limit_qps" -> ReadinessRepairAnchor("Advanced -> Relay tuning -> relay_rate_limit_qps", "Advanced config import -> relay_rate_limit_qps")
        "advanced.domain_overrides.host" -> ReadinessRepairAnchor("Advanced -> Domain overrides -> host/suffix", "Advanced config import -> domain_overrides")
        "advanced.domain_overrides.force_route" -> ReadinessRepairAnchor("Advanced -> Domain overrides -> force_route", "Advanced config import -> domain_overrides")
        "advanced.fronting_groups.name" -> ReadinessRepairAnchor("Advanced -> Fronting groups -> name", "Advanced config import -> fronting_groups")
        "advanced.fronting_groups.ip" -> ReadinessRepairAnchor("Advanced -> Fronting groups -> IP", "Advanced config import -> fronting_groups")
        "advanced.fronting_groups.sni" -> ReadinessRepairAnchor("Advanced -> Fronting groups -> SNI", "Advanced config import -> fronting_groups")
        "advanced.fronting_groups.domains" -> ReadinessRepairAnchor("Advanced -> Fronting groups -> routed domains", "Advanced config import -> fronting_groups")
        else -> null
    }
}
