#!/usr/bin/env python3
"""Generate docs parity matrix from a canonical JSON file.

Source of truth: docs/parity-matrix.json
Generated output: docs/parity-matrix.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs" / "parity-matrix.json"
OUT = ROOT / "docs" / "parity-matrix.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, list):
        if not value:
            return "-"
        return ", ".join(f"`{str(v)}`" for v in value)
    s = str(value)
    return s.replace("|", "\\|").replace("\n", " ")


def render_table(title: str, rows: list[tuple[str, dict[str, Any]]]) -> str:
    lines: list[str] = []
    lines.append(f"## {title}")
    lines.append("")
    lines.append("| Item | Desktop | Android | Runtime | Docs | CI | Examples | Notes |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for key, meta in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    cell(meta.get("label") or key),
                    cell(meta.get("desktop")),
                    cell(meta.get("android")),
                    cell(meta.get("runtime")),
                    cell(meta.get("docs")),
                    cell(meta.get("ci")),
                    cell(meta.get("examples")),
                    cell(meta.get("notes")),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def render(data: dict[str, Any]) -> str:
    modes = data.get("modes") or {}
    backends = data.get("backends") or {}
    if not isinstance(modes, dict) or not isinstance(backends, dict):
        raise ValueError("parity-matrix.json must contain objects: modes, backends")

    lines: list[str] = []
    lines.append("# Parity matrix (modes × backends × surfaces)")
    lines.append("")
    lines.append("Source of truth: `docs/parity-matrix.json`.")
    lines.append("Generated by `tools/generate-parity-matrix.py`.")
    bt = data.get("backend_taxonomy")
    if isinstance(bt, list) and bt:
        lines.append(f"Canonical backend IDs: `{', '.join(str(x) for x in bt)}`.")
        lines.append("")

    mode_rows = sorted(modes.items(), key=lambda kv: kv[0])
    backend_rows = sorted(backends.items(), key=lambda kv: kv[0])

    lines.append(render_table("Modes", mode_rows))
    lines.append(render_table("Backends", backend_rows))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("-Check", action="store_true")
    args = parser.parse_args()

    data = load_json(SRC)
    if not isinstance(data, dict):
        raise SystemExit("docs/parity-matrix.json must be a JSON object")
    out = render(data)

    if args.Check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != out:
            print(f"stale: {OUT.relative_to(ROOT)}")
            return 1
        print(f"ok parity={OUT} modes={len(data.get('modes', {}))} backends={len(data.get('backends', {}))}")
        return 0

    OUT.write_text(out, encoding="utf-8")
    print(f"wrote parity={OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

