#!/usr/bin/env python3
"""Generate/check the maintainer changelog index.

The `docs/changelog/` folder is intentionally granular. This keeps it useful by
building one navigable index from each Markdown file's first heading.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CHANGELOG_DIR = ROOT / "docs" / "changelog"
INDEX = CHANGELOG_DIR / "index.md"


def die(message: str) -> None:
    print(f"changelog index check failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    die(f"{path.relative_to(ROOT)} is missing a first-level '# ' heading")


def sort_key(path: Path) -> tuple[str, str]:
    match = re.search(r"(20\d\d-\d\d-\d\d)", path.name)
    date = match.group(1) if match else "0000-00-00"
    return (date, path.name)


def render_index() -> str:
    files = [
        path
        for path in CHANGELOG_DIR.glob("*.md")
        if path.name not in {"README.md", "index.md"}
    ]
    files.sort(key=sort_key, reverse=True)

    lines = [
        "# Changelog Index",
        "",
        "Generated by `tools/generate-changelog-index.py`.",
        "Do not edit by hand; update the source changelog files and regenerate.",
        "",
        "This index covers maintainer batch logs and per-version release-note",
        "files stored under `docs/changelog/`.",
        "",
        f"Total entries: **{len(files)}**",
        "",
        "| Date | File | Title |",
        "|---|---|---|",
    ]
    for path in files:
        match = re.search(r"(20\d\d-\d\d-\d\d)", path.name)
        date = match.group(1) if match else "n/a"
        title = first_heading(path).replace("|", "\\|")
        lines.append(f"| {date} | [`{path.name}`]({path.name}) | {title} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-Check", action="store_true", help="fail if index is stale")
    args = parser.parse_args()

    expected = render_index()
    if args.Check:
        if not INDEX.is_file():
            die(f"missing generated index: {INDEX.relative_to(ROOT)}")
        actual = INDEX.read_text(encoding="utf-8")
        if actual != expected:
            die("docs/changelog/index.md is stale; run tools/generate-changelog-index.py")
        print("changelog index check: ok")
        return 0

    INDEX.write_text(expected, encoding="utf-8")
    print(f"generated={INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
