#!/usr/bin/env python3
"""Generate/check the Android hard-coded visible-copy inventory.

This tracks intentional dynamic/technical tokens that still live in Kotlin and
fails in `-Check` mode if new localizable user-facing prose appears outside
string resources.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ANDROID_SRC = ROOT / "android/app/src/main/java/com/farnam/mhrvf"
OUT = ROOT / "docs/android-hardcoded-copy-inventory.md"

PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("Text literal", re.compile(r'Text\("((?:\\"|[^"])*)"')),
    ("Plain label", re.compile(r'\blabel\s*=\s*"([^"]+)"')),
    ("Plain title", re.compile(r'\btitle\s*=\s*"([^"]+)"')),
    ("Plain body", re.compile(r'\bbody\s*=\s*"([^"]+)"')),
    ("Plain detail", re.compile(r'\bdetail\s*=\s*"([^"]+)"')),
    ("Plain placeholder", re.compile(r'\bplaceholder\s*=\s*"([^"]+)"')),
    ("Content description", re.compile(r'\bcontentDescription\s*=\s*"([^"]+)"')),
)

IGNORE_FILES = {
    "ReadinessIds.kt",  # generated contract, not UI source.
}


def decode_literal(value: str) -> str:
    return value.replace(r"\"", '"')


def classify(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        return "ignore"
    if stripped in {"✕"} or stripped.startswith("#${") or stripped.startswith("${"):
        return "dynamic/token"
    if stripped in {"AUTH_KEY", "host:port"}:
        return "technical token"
    return "localize"


def collect() -> list[dict[str, str | int]]:
    items: list[dict[str, str | int]] = []
    for path in sorted(ANDROID_SRC.rglob("*.kt")):
        if path.name in IGNORE_FILES:
            continue
        rel = path.relative_to(ROOT).as_posix()
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            # Kotlin templates can legally contain a quoted fallback inside the
            # interpolation (`${cn ?: "(unknown)"}`), which defeats a simple
            # quote-delimited regex. Keep the known visible string intact so
            # the generated inventory does not hide the user-facing fallback.
            line_for_patterns = line
            subject_literal = 'Text("Subject: ${cn ?: "(unknown)"}"'
            if subject_literal in line:
                items.append(
                    {
                        "file": rel,
                        "line": line_no,
                        "kind": "Text literal",
                        "value": 'Subject: ${cn ?: "(unknown)"}',
                        "disposition": classify('Subject: ${cn ?: "(unknown)"}'),
                    }
                )
                line_for_patterns = line.replace(subject_literal, "", 1)
            for kind, pattern in PATTERNS:
                for match in pattern.finditer(line_for_patterns):
                    value = decode_literal(match.group(1))
                    disposition = classify(value)
                    if disposition == "ignore":
                        continue
                    items.append(
                        {
                            "file": rel,
                            "line": line_no,
                            "kind": kind,
                            "value": value,
                            "disposition": disposition,
                        }
                    )
    return items


def markdown(items: list[dict[str, str | int]]) -> str:
    localize = sum(1 for item in items if item["disposition"] == "localize")
    token = sum(1 for item in items if item["disposition"] != "localize")
    lines = [
        "# Android Hard-Coded Copy Inventory",
        "",
        "Generated by `tools/generate-android-hardcoded-copy-inventory.py`.",
        "Do not edit by hand; move literals to string resources or update the scanner.",
        "",
        f"- Total visible hard-coded literals: **{len(items)}**",
        f"- Should move to string resources: **{localize}**",
        f"- Dynamic/technical tokens to review separately: **{token}**",
        "",
        "| File | Line | Kind | Text | Disposition |",
        "|---|---:|---|---|---|",
    ]
    for item in items:
        text = str(item["value"]).replace("|", "\\|")
        lines.append(
            f"| `{item['file']}` | {item['line']} | {item['kind']} | "
            f"`{text}` | {item['disposition']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-Check", action="store_true", help="fail if generated doc is stale")
    args = parser.parse_args()

    items = collect()
    output = markdown(items)
    if args.Check:
        if not OUT.is_file():
            print(f"missing generated inventory: {OUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n")
        if current != output.replace("\r\n", "\n"):
            print(
                "Android hard-coded copy inventory is stale. "
                "Run tools/generate-android-hardcoded-copy-inventory.py.",
                file=sys.stderr,
            )
            return 1
        localize_items = [item for item in items if item["disposition"] == "localize"]
        if localize_items:
            print(
                "Android hard-coded copy inventory has localizable literals; "
                "move them to string resources instead of carrying them as inventory:",
                file=sys.stderr,
            )
            for item in localize_items:
                print(
                    f"- {item['file']}:{item['line']} {item['kind']}: {item['value']}",
                    file=sys.stderr,
                )
            return 1
        print(f"Android hard-coded copy inventory check: ok literals={len(items)} localize=0")
        return 0

    OUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"generated={OUT.relative_to(ROOT)} literals={len(items)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
